### ISSUE TITLE
Improve healthcheck

### ISSUE THREAD

**Issue by rahulreddy** [scality/utapi#103]
Current healthcheck checks if the server is ready. This is not enough data as there are some corner cases where the server reports that its ready but there could be other issues like there is no more Sentinel quorum, Sentinels have no slaves etc. There are two tasks that needs to be achieved.
1) Compile a list of Redis checks
We can sift through the list and identify which are actually needed
2) Incorporate the checks with healthcheck handler

Note: Make sure that the checks do not perform any blocking operation.

**Comment by bennettbuchanan** [comment]
Let's add a ticket in Jira if we want to revisit this.
