### ISSUE TITLE
storage used and number of objects counters should not go below 0

### ISSUE THREAD

**Issue by rahulreddy** [scality/utapi#105]
It's possible that Utapi "missed" (when Redis is down etc) some api actions like PUT and only recorded DELETEs, the storage could be decremented to below 0. Though this should not happen in a perfect world, it does and it affects the counter when we increment the storage used on new PUTs.
Make sure storage is never decremented below 0, and add a warning log.

Fix should target 6.3

**Comment by bennettbuchanan** [comment]
Fixed by https://github.com/scality/utapi/pull/108.
