### ISSUE TITLE
Transient buckets

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/utapi#25]
Since s3 will send an error response if a transient bucket is created and then actually create the bucket on a putObject or putObjectACL call, utapi will miss pushing the create bucket metric (and won't 0 out the metrics if there was a prior bucket with the same name).  A push metrics call needs to be added in s3 in lib/api/bucket/bucketCreation.js.

Similarly, there are invisiblyDelete calls if a bucket deletion failed part way through.  So, a push metrics call needs to be added in s3 in lib/api/bucket/bucketDeletion.js.

**Comment by bennettbuchanan** [comment]
Adding a ticket ZENKO-1474 in Jira for tracking. Closing this as we're moving away from managing issues through GitHub.
